### ISSUE TITLE
Crash when installed alongside Thaumcraft

### ISSUE THREAD

**Issue by Lenvill-Jarlsen** [PIPPIP5789/EoMFR#1]
Hello,
It appears this mod is currently conflicting with Thaumcraft. When Thaumcraft is installed alongside this mod (plus the necessary prerequisites, of course), it causes MFR to crash due to a "java.lang.ArrayIndexOutOfBoundsException" at "minefantasy.mfr.recipe.CraftingManagerAnvil.addRecipe(CraftingManagerAnvil.java:138)"
Full crash report below. I've also shared this on the MFR discord server, but ThatPolishKid couldn't glean much from the crash report.
[crash-2023-01-23_14.40.21-client.txt](https://github.com/PIPPIP5789/EoMFR/files/10483260/crash-2023-01-23_14.40.21-client.txt)

**Comment by PIPPIP5789** [comment]
Heyo!
So, looking through the report, what were you doing when this crashed? Were you attempting to create something on an anvil? Or did this crash during the startup of the game itself?

**Comment by Lenvill-Jarlsen** [comment]
It occurred during game launch. I started the game with unmodified config files too.

**Comment by PIPPIP5789** [comment]
Sorry for the delayed response, been pretty busy recently.

Alright, so... did some research and managed to recreate the bug. I know what's causing it - Thaumcraft has its own versions of lead, and for some reason, MineFantasy is throwing a fit when I try to call the OreDict for a lead nugget specifically. It's trying to iterate over something more than it should, so my best guess is that it's trying to iterate over the oredict:nuggetLead more than it should. Why it's doing that, I'm not really sure, but I've been able to at least fix it, so it should be working properly in the next update of EoMFR.

Thank you for the report!
